### ISSUE TITLE
I find some problems

### ISSUE THREAD

**Issue by A0000Xz** [DrexHD/Vanish#34] opened 2024-02-04 15:51 UTC
Mod Version:vanish-1.4.2+1.20.jar
Minecraft Version:1.20.1
1,Vanished players can throw items but cannot pick them up. Interestingly, items thrown by vanished players also remain vanished, yet normal players can pick them up as usual.
2,Vanished players can be pushed by regular players without obstructing them. However, vanished players obstruct regular players from placing blocks, and projectiles from players are also blocked by them.
3,Vanished players do not attract hostility from mobs, except for the warden. The warden, when attacked by a vanished player in survival mode, cannot target and attack the vanished player but will continuously face the vanished player and emit a roaring animation (the angry action).
4,Vehicles occupied by vanished players act as if there is a visible player inside. Similar to visible players, vanished players will be ejected from minecarts when activated on activator rails, and they will block vehicles. However, it is preferred that vanished players do not obstruct vehicles.
5,Vanished players opening chests indeed have no animation or sound. However, if at the same time a visible player and a vanished player both open the same chest, and the visible player closes it first, the visible player will see the chest remaining open until the vanished player closes it. This behavior applies to barrels, trapped chests, and ender chests as well, but interestingly, shulker boxes do not exhibit the same behavior.
6,Vanished players will trigger raids as long as they have the Bad Omen potion effect in on them.
7,The Secret Spectator mod conflicts with the Vanish mod. Through testing, if a vanished player exits vanish while in spectator mode, other players can see that the name of the player who exited vanish is in gray on TAB (indicating spectator mode). This bug persists until any player switches modes.

My English is not very good. I have used translation software in some places. If there are any interesting errors, please forgive me.But please fix these issues, this mod is really good.

**Comment by A0000Xz** [comment] 2024-02-04 15:57
Oh, I should add.The Secret Spectator Mod Version: secret-spectator-1.0.3.jar

**Comment by DrexHD** [comment] 2024-02-04 18:33
> 1,Vanished players can throw items but cannot pick them up. Interestingly, items thrown by vanished players also remain vanished, yet normal players can pick them up as usual.

This is intentional. Most entities "created" by vanished players will be invisible (useful for projectiles, flying with elytra (spawns rockets) and more). You can enable item pickup in the config by setting `interaction.entity-pickup` to `false`

>  2,Vanished players can be pushed by regular players without obstructing them. However, vanished players obstruct regular players from placing blocks, and projectiles from players are also blocked by them.

It is also intentional that vanished players can be pushed by regular players (this mods main focus is just to hide the vanished players). It is not intentional that vanished players prevent block placement, this needs to be fixed. Projectiles are not blocked by vanished players!

>  3,Vanished players do not attract hostility from mobs, except for the warden. The warden, when attacked by a vanished player in survival mode, cannot target and attack the vanished player but will continuously face the vanished player and emit a roaring animation (the angry action).

This is intentional, if you want hostile mobs to target vanished players set `hide-from-entities` to `false`

>  4,Vehicles occupied by vanished players act as if there is a visible player inside. Similar to visible players, vanished players will be ejected from minecarts when activated on activator rails, and they will block vehicles. However, it is preferred that vanished players do not obstruct vehicles.

This is unfortunate, but I don't know of any way to work around this. The intention of this mod is that for the server everything is normal and there is no way to properly store two players in the same vehicle.

>  5,Vanished players opening chests indeed have no animation or sound. However, if at the same time a visible player and a vanished player both open the same chest, and the visible player closes it first, the visible player will see the chest remaining open until the vanished player closes it. This behavior applies to barrels, trapped chests, and ender chests as well, but interestingly, shulker boxes do not exhibit the same behavior.

This is a known (vanilla) bug. The same thing happens with a player in spectator.

>  6,Vanished players will trigger raids as long as they have the Bad Omen potion effect in on them.

This is also something that could be fixed in a future update.

>  7,The Secret Spectator mod conflicts with the Vanish mod. Through testing, if a vanished player exits vanish while in spectator mode, other players can see that the name of the player who exited vanish is in gray on TAB (indicating spectator mode). This bug persists until any player switches modes.

Mmh, this might be a bit annoying to fix from this mod. That incompatibility is likely caused by [this line](https://github.com/DrexHD/Vanish/blob/1.20.3/src/main/java/me/drex/vanish/util/VanishManager.java#L130). Secret Spectator mod would have to change their approach and modify packets similar to the vanish mod in [ServerCommonPacketListenerImplMixin](https://github.com/DrexHD/Vanish/blob/1.20.3/src/main/java/me/drex/vanish/mixin/ServerCommonPacketListenerImplMixin.java)

**Comment by A0000Xz** [comment] 2024-02-06 01:21
> It is also intentional that vanished players can be pushed by regular players (this mods main focus is just to hide the vanished players). It is not intentional that vanished players prevent block placement, this needs to be fixed. Projectiles are not blocked by vanished players!

But I'm sure the Vanished player will block the projectile.
![2024-02-06_09 14 15](https://github.com/DrexHD/Vanish/assets/122650088/66108895-ec8f-4561-b2ed-852e0379399d)
![2024-02-06_09 14 22](https://github.com/DrexHD/Vanish/assets/122650088/22dac1db-39fb-46c4-a5f1-ac54792520b3)


> This is intentional, if you want hostile mobs to target vanished players set to `hide-from-entities``false`

I actually want the warden to no longer notice vanished players about this point.Because the warden's behavior is that after being attacked, at least vanished players can be seen.


> This is unfortunate, but I don't know of any way to work around this. The intention of this mod is that for the server everything is normal and there is no way to properly store two players in the same vehicle.

The key issue is that vanished players may block vehicles such as ships and mining carts.
![2024-02-06_09 18 04](https://github.com/DrexHD/Vanish/assets/122650088/08761ddf-ea6c-4875-9c74-4ca4f006016a)
![2024-02-06_09 18 10](https://github.com/DrexHD/Vanish/assets/122650088/041f7d15-921d-43d3-8fa2-8984bbc07630)

**Comment by DrexHD** [comment] 2024-02-06 09:20
Oh, I just noticed you are using an outdated version. All of the features you requested have already been implemented, but only for the most recent Minecraft version. You can take a look at this [changelog](https://github.com/DrexHD/Vanish/blob/1.20.3/CHANGELOG.md#142---2023-06-09) (everything above that line was changed in newer versions)

**Comment by A0000Xz** [comment] 2024-02-07 14:09
> Oh, I just noticed you are using an outdated version. All of the features you requested have already been implemented, but only for the most recent Minecraft version. You can take a look at this [changelog](https://github.com/DrexHD/Vanish/blob/1.20.3/CHANGELOG.md#142---2023-06-09) (everything above that line was changed in newer versions)

Um, can the latest MOD adapt to version 1.20.1?

**Comment by DrexHD** [comment] 2024-02-10 12:35
I have backported the latest version to 1.20.1! I have also added a fix for vanished players spawning raids!

**Closed by DrexHD** 2024-02-10 12:35 UTC
